### ISSUE TITLE
text entry issue on iPad

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#150]
text entry issue on iPad where the keyboard can on occasion obscure the text field making it impossible for learners to see what they are writing.  This can be fixed by closing and opening the keyboard a few times.

**Comment by olesm** [comment]
The teacher sent us an image; iPad landscape

**Comment by nesnass** [comment]
iPad running iOS10 seems to work fine; we need to see the problem before diagnosing it. Can you find a way to replicate it?

**Comment by olesm** [comment]
This is the image I got. This could be an iPad mini from. I can ask them about the iOS version. 
![image001](https://cloud.githubusercontent.com/assets/1403494/19073973/235cce4c-8a3e-11e6-9aed-19d01dc0b1ea.png)

**Comment by olesm** [comment]
Tried it on a iOS9 mini iPad. The only way I could reproduce is to first open the keyboard (happens automatically), then rotate the device. Then you get a situation like the one above. Maybe not the highest priority.

**Comment by olesm** [comment]
OK, tested
