### ISSUE TITLE
Export to NVivo

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#160]
Add page that displays log data as csv. Input is a session id. Meant to be imported to NVivo.

**Comment by nesnass** [comment]
@olesm Should this export be protected by requiring a logged in user?  Otherwise, it can simply be a second field where a Wall ID is entered, on the 'ID' screen.
Also, can the user easily get hold of the Wall ID before & after closing the wall?

**Comment by olesm** [comment]
I do think we need to protect the log data. I suggest we keep the ID screen as is (unauthenticated), and add an authenticated route to get the csv data (and eventually data for visualization). This route can be just /#/LA/ (for learning analytics). It will only be us researchers in DiDiAC who will access this functionality, and we need a simple means to tell the server who can access LA (could be a simple as a text file with 10 or so fb/google names).

**Comment by nesnass** [comment]
We would need to use the wall ID as the identifier. Can the researchers obtain that ID easily enough? At this point I think it's only available from the /ID page, which in turn is only available while the pin is active..

Richard

**Comment by olesm** [comment]
Good question, this is why it is important to show the mobile screen with the ID page to the camera. There should probably be another way to find the log data also, such as browsing. I'll give this last idea some thought and we can discuss Monday.

**Comment by olesm** [comment]
We have discussed this further. There should be two functions for this, one for NVivo import, the other for use outside NVivo. I'll create a new epic for the one that will be outside (to be dealt with later). For the import, we need a csv file to be downloaded based on Wall ID. There is an attachment that shows the format of this file. User input and some computation is required to figure out the 'Minutes into session' column. 
[Copy of Hammer-Norsk-151211-Are-messages.xlsx](https://github.com/engagelab/talkwall/files/708292/Copy.of.Hammer-Norsk-151211-Are-messages.xlsx)

**Comment by olesm** [comment]
Suggestion:
A page with two forms:

Top form:
Heading: Select log data
- entry : Wall ID
- list of all dates for this Wall ID -> user picks one (usually there will be one)

Bottom form:
Heading: Compute relative timespans for NVivo
Text: Locate the filmed ID screen in the video. Make a note of the timespan value on the timeline. 

- entry : the time from the ID screen
- entry : the timespan value on the timeline (h:mm:ss)

Download button 
Text: GET LOG (CVS)
-> computes the 'Minutes into session' column.
- compute diff in seconds between the time for the first contribution and the time from the ID screen
- take diff and add the timespan value -> Minutes into session (use h:mm:ss format)

**Comment by olesm** [comment]
This is a sketch for the export form.
![export-form](https://cloud.githubusercontent.com/assets/1403494/22144725/f6d91b44-defe-11e6-9b04-97d9cc71486e.jpg)
