### ISSUE TITLE
PRI #1: Organisers can resume previous sessions

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#163]
### Organise panel on Landing page
* Selecting “JOIN”: same functionality as today
* Selecting ”CREATE” -> authentication (as now + PRI #6) -> new organise panel:

(see also proto.io)

Elements:

1. name: “Your Talkwall sessions”

1. top: person icon + text field: nickname of organiser (fetched from db if present)

1. list in two parts: 
   heading “recent”
   
   1. recent sessions (max 4) sorted by last opened date
   
   heading “all”
   
   1. all sessions (‘auto folder’) sorted alphabetically by group, then theme
		
1. two input fields: ’Group’ and ’Theme’

1. FAB button (+): Create new session (using values for Group and Theme if present)

* session item:
** 2 lines:
````
group/theme/status/date
X contributions, Y tasks: <start of task 1 wording>
````
* status: other organisers if any (PRI #2) + locked (icon) or pin code
* date: for recent list: relative date (e.g. 7d), else actual date (e.g. 11. Nov 2016)
* ‘auto folder’: if sessions with same value for Group > 4:
  ** display these sessions in collapsible list (see proto.io)

* session item menu:
**	status: locked/unlocked toggle
**	edit (change values for Group and Theme)
**	PRI #2: add organiser -> new add organiser panel
**	PRI #5: share as template -> new share panel
**	delete (mark as deleted in db)

### Right side panel
* Remove email field on closing panel. 
* Add toggle: lock/unlock -> set session as locked -> this disconnects all connected users
* Close just return to organize panel.

**Comment by nesnass** [comment]
All complete except for 'auto folder' feature
Requires initial testing
