### ISSUE TITLE
filter on participants

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#26]
Expand "Filter messages" panel in sidepanel-right

list at the top all Nicknames with a checkbox 

Apply a combined filter (participants AND hashtags) to messages on wall and on feed - indicate active filters in panel name

**Comment by nesnass** [comment]
Filter by nicknames is operational. 
Applied to wall, but not yet to the feed.

Questions:
 * Should 'nickname' filter be in a separate panel to the 'hashtag' filter or combined?

**Comment by jt151077** [comment]
fixed
