### ISSUE TITLE
Limit nickname length

### ISSUE THREAD

**Issue by nesnass** [engagelab/talkwall#280]
Some users are creating long nicknames that produce incredibly long poll requests:

e.g. the nickname 

Cole⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️⚽️

translates in a request as

Cole%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F%E2%9A%BD%EF%B8%8F

**Comment by nesnass** [comment]
@olesm Can you suggest a maximum number of chars for the nickname?

**Comment by olesm** [comment]
This will have to work for chips as well, so I suggest to limit both in length and value. I suggest you make a constant somewhere, so we can change easily. Set it to 15 chars max for now. No emojis.
