### ISSUE TITLE
Add task header

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#287]
When creating new talkwall it says in header "add task" while the right menu says "edit task".

**Comment by olesm** [comment]
This is OK, as the right hand panel opens and reveal the "add task" button

**Comment by nesnass** [comment]
We can both 'add' and 'edit' Tasks in that panel.  Similarly 'Show PIN' also shows other information.
Is it a good idea to use more general single word titles e.g 'Tasks' and 'Info' or 'Details' ?

**Comment by olesm** [comment]
I think the current text for the task panel is fine. The PIN panel has one main role, and I think that should be in the title. In Norwegian it is "Delta med PIN" and I like the verb orientation. Hence, in English: "Participate with PIN"
