### ISSUE TITLE
find new select icon for mesages

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#29]
sidepanel-left

    "Messages" tab
        message feed
            message
                controllbar
                    icons may need updating

(e.g. lightbulb)

**Comment by olesm** [comment]
I suggest to swap the lightbulb and the pin. 
Pin is to stitch messages on the feed onto the board.
Lightbulb is to mark messages on the board as important (and for copy to a different wall).

**Comment by jt151077** [comment]
fixed
