### ISSUE TITLE
Use full name in "Your Talkwalls" list of Talkwalls ?

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#305]
When a Talkwall is shared the nick is displayed in the list. It may be better to use full name here.

We need to discuss.

**Comment by nesnass** [comment]
For now I've removed the nickname from the organiser. You must go to 'edit' mode on a Wall to see the list of shared organisers (as emails)

**Comment by olesm** [comment]
I think this is fine. We leave it at it is now.
