### ISSUE TITLE
Entries in "Your Talkwalls" in Safari (both desktop and iPad)

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#320]
to reproduce:
- open talkwall as organiser
- open hamburger for any existing talkwall
- the field is compressed, and fields are overlapping

**Comment by nesnass** [comment]
This function works fine and looks great on both Safari Mac and Safari iOS on the iPad in the lab!

**Comment by nesnass** [comment]
Ah I see there is a problem in the 'edit' panel.
