### ISSUE TITLE
2 field selectors for NVivo are confusing

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#322]
![screen shot 2017-01-30 at 16 06 07](https://cloud.githubusercontent.com/assets/1403494/22428107/1b87d91c-e706-11e6-8724-d1ad9ff1f726.png)

The timespan value in NVivo is h:mm:ss (not date)

The lenght of clip is also h:mm:ss (not date)

**Comment by nesnass** [comment]
There is no other decent time picker available that includes seconds. So I am using the same date/time picker for all fields. Will try to find a way to disable the 'date' part of the display in the second and third fields..
