### ISSUE TITLE
The "GET CSV" doesn't work

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#323]
to reproduce:
- select values and wallID in the nvivo form
- select GET CSV 

- noting happens

**Comment by nesnass** [comment]
Need some more info - which wall ID, which date and range?
It's possible your wall has no logs in the date range or is not set to be tracked at all

**Comment by olesm** [comment]
587e49cbf600a7000482a1bd
Around 20 hours ago there should be some events
If this is not set, you could add me as someone to be tracked.

**Comment by nesnass** [comment]
No one except me is currently being tracked. As I asked last week we need the email addresses of those you want to track. Otherwise, it is working, just producing an empty CSV file. I set the date to 1 day ago and the clip length to 23:59:59.
