### ISSUE TITLE
Facebook authenticated users don't have Fullname and email

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#325]
A facebook user looks typically like this, i.e. no defaultEmail and undefined for facebook.name

{
    "_id": {
        "$oid": "57cd2070a4368e03004da862"
    },
    "helpViewed": false,
    "lastOpenedWall": {
        "$oid": "57cd2071a4368e03004da863"
    },
    "nickname": "teacher",
    "google": {
        "createdAt": {
            "$date": "2016-09-05T07:36:16.105Z"
        }
    },
    "facebook": {
        "name": "undefined undefined",
        "token": "EAAPQFJoPkbUBAEBi2EZAhMXWnJBXqZCUZB2CEl8GeHZBNKfyRPDgFZAcK8pr54khEZCk1ZBdZADcuv4gYDGQ1aZAwF9KWZC3ni9KnDX7TwNdrqLqPtiAt0PKQTVBj4fBtLL3rJcSNGZBO6nRWU7cob69Eu3zM34PUPZCZBnIZD",
        "id": "10157401963795254",
        "createdAt": {
            "$date": "2016-09-05T07:36:16.105Z"
        }
    },
    "local": {
        "createdAt": {
            "$date": "2016-09-05T07:36:16.105Z"
        }
    },
    "__v": 0
}

**Comment by nesnass** [comment]
Facebook auth was not working correctly
Needed to update some settings on Facebook and our server..
Will be operational on next push

**Comment by olesm** [comment]
The name and email are now transferred from Facebook. Old entries in mongo are not updated, so this may be added to the auth.
