### ISSUE TITLE
Production server: App crash

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#330]
1 Feb 2017 09:12:18.122 156 <190>1 2017-02-01T08:12:17.905087+00:00 app web.1 - - /app/node_modules/newrelic/lib/transaction/tracer/index.js:191
» 1 Feb 2017 09:12:18.123 109 <190>1 2017-02-01T08:12:17.905236+00:00 app web.1 - - throw err
» 1 Feb 2017 09:12:18.123 101 <190>1 2017-02-01T08:12:17.905249+00:00 app web.1 - - ^
» 1 Feb 2017 09:12:18.123 94 <190>1 2017-02-01T08:12:17.905260+00:00 app web.1 - -
» 1 Feb 2017 09:12:18.123 150 <190>1 2017-02-01T08:12:17.905272+00:00 app web.1 - - TypeError: Cannot read property 'questions' of undefined at Mm.postUpdate (/app/config/message_manager.js:291:48) at /app/routes/teacher.js:612:16 at /app/node_modules/mongoose/lib/model.js:3388:16 at /app/node_modules/mongoose/lib/document.js:1997:18 at wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:183:28) at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
» 1 Feb 2017 09:12:18.306 124 <45>1 2017-02-01T08:12:18.004557+00:00 heroku web.1 - - Process exited with status 1
» 1 Feb 2017 09:12:18.310 355 <158>1 2017-02-01T08:12:17.892836+00:00 heroku router - - at=error code=H13 desc="Connection closed without response" method=GET path="/messages/589193ed25a71d0004802de3" host=www.samtavla.no request_id=9a2b768a-dce4-422d-8f6f-b1e07e52719f fwd="195.159.223.12" dyno=web.1 connect=0ms service=37ms status=503 bytes=0 Critical
» 1 Feb 2017 09:12:18.341 128 <45>1 2017-02-01T08:12:18.001682+00:00 heroku web.1 - - State changed from up to crashed
» 1 Feb 2017 09:12:18.478 390 <158>1 2017-02-01T08:12:17.895743+00:00 heroku router - - at=error code=H13 desc="Connection closed without response" method=GET path="/poll/Emil/589193b925a71d0004802de2/589193ed25a71d0004802de3/none/new" host=www.samtavla.no request_id=787e48ea-81e2-4d1a-9db2-abe398fb44a8 fwd="195.159.223.12" dyno=web.1 connect=0ms service=32ms status=503 bytes=0 Critical
»

**Comment by nesnass** [comment]
This should be fixed in the new version

**Comment by olesm** [comment]
Yes, I assumed it was fixed, but wanted to be sure.
