### ISSUE TITLE
Teacher editing pinned messages on participants' walls.

### ISSUE THREAD

**Issue by jandolonen** [engagelab/talkwall#436]
1. Teacher wants to look at students' walls.
2. Teacher chooses one of the students walls. That student has pinned a message.
3. If teacher now edits that particular message in the participants' view that student will not see the update neither in his version of the pinned message or in his feed if he is the one that created that message in the first place. However, the teacher and all other students will see an updated version of that particular message in the feed (and on their wall in case they have pinned it as well).
4. If the student is not the one that created that message in the first place and the teacher updates the pinned message in the participants' view, the student will see a new message in the feed but he will not see any update of his pinned message.

**Comment by nesnass** [comment]
This is deliberate. There are some implementation problems involved with a user editing a different user's message, but in addition we never stated that this was a requirement.
