### ISSUE TITLE
Screens Tab

### ISSUE THREAD

**Issue by nesnass** [engagelab/talkwall#81]
* client list
	* client
		* standard icon (same but for the teacher -> crown)
		* nickname
		* select checkbox (selected -> display client's task wall same as teacher's task number)
	* select all button checks all checkboxes (-> unselect all button, but keep the teacher)

**Comment by nesnass** [comment]
Selection panel is ready (left hand menu).
Requires a new server route to request on-wall messages for a particular set of users

Questions: 
 * Should the feed also be a combined view of all checked clients?
 * How does polling work in this scenario?
 * Do we disable creation of new messages in this mode, as the view of other walls is 'read only'?

**Comment by nesnass** [comment]
This list changes as we watch - because it is based dynamically on 'currently active' nicknames.
The server removes nicknames after a period (10s) if inactive.
Is this desirable?

**Comment by jt151077** [comment]
the screen tab allows only switching between single users via a radiobutton

**Comment by jt151077** [comment]
fixed
