### ISSUE TITLE
Messages: edit

### ISSUE THREAD

**Issue by nesnass** [engagelab/talkwall#82]
if not owner of the message, create a copy, inherit history and metadata, and appends to the message feed. keep originator message ID.

**Comment by nesnass** [comment]
"On Wall" Message" -  if not owner of the message (revision 01/06):
						 * create a copy (clone and get a new message id)
						 * inherit history and metadata
						 * inherit position x. y
						 * appends to the message feed.
						 * place the new maessage on board on previous position
						 * remove origin message from board

**Comment by jt151077** [comment]
fixed
