### ISSUE TITLE
Styling: improvements

### ISSUE THREAD

**Issue by nesnass** [engagelab/talkwall#88]
Improve Margins across site

Review and improve icons used

sidepanel-left -> "Messages" tab -> message feed -> message
   *  (+) button can be turned transparent and list all the way to the bottom
   * history chips needs to be restyled
   * controllbar
   * icons may need updating

when question is 'force-changed' by teacher, client background colour does not update

**Comment by jt151077** [comment]
everything fixed, apart from a weird bug on safari desktop. A white margin appears in the control bar of feed messages, and disappears during the next redraw cycle. Have googled but without any luck. Richard did observe the same phenomena without any solutions
