### ISSUE TITLE
Colours

### ISSUE THREAD

**Issue by nesnass** [engagelab/talkwall#93]
Find suitable colours for background and to complement background

Current selection (not ideal!):

BACKGROUND_COLOURS: ["#CDCC43", "#D74FD3", "#D04538", "#6CCFCB", "#4F3862", "#4C3E23", "#C58178", "#C74686", "#5D76C8", "#557D36"]

 COMPLEMENTARY_COLOURS: ['#693289', '#DEFB5C', '#2A9D44', '#FFBB85', '#928F4F', '#1A2233', '#5A9369', '#A7DE4E', '#FFCF65', '#7F374B']

**Comment by olesm** [comment]
We used these colors in the first version to differentiate between the speech bubbles, right?

**Comment by nesnass** [comment]
No don't think so, took these colours from Visitracker project!
I think we need a complementary set so that grid lines show clearly on top of background. But we only need 10 in total, as there are max 10 questions.

**Comment by olesm** [comment]
I think the complementary colour (background lines) should be white-ish (#FFFFF5) on all walls.

This is a set we can start with:
    #5E7E98
    #666666
    #6D8565
    #7A7A7A
    #828565
    #858585
    #8EBEE6
    #998C5F
    #999999
    #ABD19F
    #CDD19F
    #E6C48E

(generated here: http://www.colorblender.com/?preloadblend=5E7E988EBEE6998C5FE6C48E666666999999)
